Repository i-Dear/sync-d-frontend, pull requests merged in 2024-06, with the labels that each got.

#143 [Fix] 142: draggable false 추가, layout 제거
  src/components/CanvasLayer/Sticker.tsx
Labels: bug

#148 [#146] Feat: 상단바 초대 모달, 유저 정보 수정, sendbird 오류, nextconfig수정, 레거시 삭제 #146
  next.config.mjs
  src/app/(user)/layout.tsx
  src/app/page.tsx
  src/components/Layout/CollabToolAside/GroupCall/GroupCallButton.tsx
  src/components/Layout/LeftNav/NavLinks.tsx
  src/components/Layout/TopNavBar.tsx
  src/components/Modals/InviteModal.tsx
  src/components/Modals/UserInfoModal.tsx
  src/components/Modals/index.tsx
  src/components/UserInfoSettingBar.tsx
Labels: feature, fix, publish

#147 [#132] Fix: 실시간 다중 유저가 각 노드를 동시 편집 할 때 변경 사항이 반영되지 않고 버벅이는 이슈 해결
  liveblocks.config.ts
  next.config.mjs
  src/components/ReactFlowCanvas/Node/ContentNode.tsx
  src/components/ReactFlowCanvas/Node/MiddleNode.tsx
  src/components/ReactFlowCanvas/Node/PageNode.tsx
  src/components/ReactFlowCanvas/Node/StakeholderNode.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/components/Room.tsx
  src/lib/guard.ts
  src/lib/types.ts
  src/lib/useNodes.ts
  src/lib/utils.ts
Labels: bug, jjunohj, fix

#150 [#149] Fix: Reactflow 캔버스를 사용하는 단계에서 Liveblocks 툴바가 보이는 이슈 해결
  src/components/Canvas/index.tsx
  src/components/CanvasToolBar/CanvasButton.tsx
  src/components/CanvasToolBar/index.tsx
Labels: jjunohj, feature

#152 [#151] Feat: 텍스트 색깔 추가
  src/components/CanvasLayer/Text.tsx
Labels: jjunohj, feature

#154 [#153] Feat: 드래그 상호작용 시 정적 템플릿 텍스트가 드래그되는 현상 방지
  src/components/ProcessContent/GuideTextBox.tsx
  src/components/ProcessContent/NoteBox.tsx
  src/components/ProcessContent/VoteBox.tsx
  src/components/ReactFlowCanvas/Node/AnnotationNode.tsx
  src/components/ReactFlowCanvas/Node/AreaNode.tsx
Labels: jjunohj, feature

#156 [#155] Feat: 3차 QA 이슈 해결 (링크 첨부)
  src/components/Canvas/ColorPicker.tsx
  src/components/CanvasLayer/Sticker.tsx
  src/components/Common/Carousel.tsx
  src/components/GuideCarousel.tsx
  src/components/Modals/VoteCompleteModal.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectDetailBox.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/nodes.ts
Labels: jjunohj, feature, fix, publish

#160 [#159] 프로젝트 이미지, 진척도, 기여자 수 데이터 적용, 프로젝트 진척도 업데이트 로직 구현
  public/confetti.png
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/Layout/CollabToolAside/ProgressBar.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectCards.tsx
  src/lib/data.ts
  src/lib/types.ts
Labels: jjunohj, feature, publish

#161 [#158] Feat: 3차 QA 반영
  liveblocks.config.ts
  src/components/Canvas/SelectionTools.tsx
  src/components/Canvas/index.tsx
  src/components/CanvasLayer/Vote.tsx
  src/components/Modals/SyncModal.tsx
  src/components/ProcessContent/PersonaBox.tsx
  src/components/ProcessContent/VoteBox.tsx
  src/components/Room.tsx
  src/hooks/useDeleteLayers.ts
  src/hooks/useDeleteLayersBackspace.ts
  src/lib/templates.ts
  src/lib/types.ts
  src/utils/processSync.ts
Labels: feature, refactor

#164 [#157] Feat: reactflow 활용 기획 단계 결과물 캡처 후 이미지 전송 로직 구현
  package-lock.json
  package.json
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/data.ts
  src/lib/nodes.ts
  src/lib/types.ts
  src/lib/utils.ts
Labels: jjunohj, feature

#167 [#163] Style: 템플릿 리사이즈
  src/components/CanvasLayer/Persona.tsx
  src/components/CanvasLayer/Vote.tsx
  src/components/ProcessContent/EpicBox.tsx
  src/components/ProcessContent/PersonaBox.tsx
  src/components/ProcessContent/VoteBox.tsx
  src/lib/templates.ts
Labels: jjunohj, feature, publish

#170 [#169] Chore: 결과물 PDF 파일 요청 HTTP 메소드 변경, 새 탭으로 띄우도록 변경
  src/components/Modals/CompleteModal.tsx
  src/components/ProjectCard.tsx
  src/lib/data.ts
Labels: jjunohj, feature

#172 [#171] Feat: 아이패드 관련 QA 적용, 우측 툴바 서랍효과 적용
  src/app/layout.tsx
  src/components/CanvasLayer/Epic.tsx
  src/components/Layout/CollabToolAside/MusicPlayer/index.tsx
  src/components/Layout/CollabToolAside/index.tsx
  src/components/Layout/RootLayout.tsx
  src/components/ReactFlowCanvas/Node/MiddleNode.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/utils.ts
Labels: jjunohj, feature

#173 [#171] Fix: 모바일 검색바 반영 높이 수정
  src/app/(user)/layout.tsx
  src/app/board/layout.tsx
  src/app/layout.tsx
  src/components/Layout/CustomLayout.tsx
  src/components/Loading.tsx
Labels: jjunohj, fix
