Repository i-Dear/sync-d-frontend, pull requests merged in 2024-05, with the labels that each got.

#46 [#40] Feat: 상단바 UI 구현
  public/bell.svg
  public/logo.svg
  src/app/layout.tsx
  src/components/TopNavBar.tsx
Labels: jjunohj, feature, publish

#44 [#43] Feat: 랜딩페이지 구현
  public/google-logo.svg
  public/landing-logo.svg
  src/app/page.tsx
  src/components/GoogleLogin.tsx
  tailwind.config.ts
Labels: jjunohj, feature, publish

#48 [#47] Feat: 좌측 프로세스 바 로직 및 UI, 애니메이션 구현
  liveblocks.config.ts
  public/help.svg
  public/menu.svg
  src/components/Canvas.tsx
  src/components/ProcessSideNav.tsx
  src/components/Room.tsx
  src/lib/data.ts
  tailwind.config.ts
Labels: jjunohj, feature, publish

#52 [#38] Feat: 가이드 모달 작업
  package-lock.json
  package.json
  public/steps/stepguide1.png
  public/steps/stepguide2.png
  public/steps/stepguide3.png
  src/components/Canvas/index.tsx
  src/components/Common/Button.tsx
  src/components/Common/Carousel.tsx
  src/components/GuideCarousel.tsx
  src/components/GuideModal.tsx
  src/components/Layout/CollabToolAside/Timer.tsx
  src/components/Layout/ProcessNav/index.tsx
  src/components/SkipModal.tsx
  src/lib/guideImages.ts
  src/store/useModalStore.ts
Labels: feature

#55 [#51] Feat: 템플릿 적용에 관한 캔버스 시스템 로직 구현
  liveblocks.config.ts
  src/components/Canvas/TemplateComponent.tsx
  src/components/Canvas/index.tsx
  src/components/ProcessContent/NoteBox.tsx
  src/components/Room.tsx
  src/lib/templates.ts
  src/lib/types.ts
  tailwind.config.ts
Labels: jjunohj, feature, publish

#57 [#53] Feat: 모달 리팩토링, 스킵 모달 mutation
  src/components/Canvas/index.tsx
  src/components/Layout/ProcessNav/index.tsx
  src/components/Modals/GuideModal.tsx
  src/components/Modals/SkipModal.tsx
  src/components/Modals/index.tsx
  src/components/SkipModal.tsx
  src/store/useModalStore.ts
Labels: feature, refactor

#61 [#60] Feat: 캔버스 버튼 - Skip, Vote, 버튼 구현, 투표 및 완료 모달 구현, Sync 퍼블리싱
  src/components/CanvasToolBar/CanvasButton.tsx
  src/components/CanvasToolBar/SkipButton.tsx
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/CanvasToolBar/VoteButton.tsx
  src/components/CanvasToolBar/index.tsx
  src/components/Layout/ProcessNav/index.tsx
  src/components/Modals/CompleteModal.tsx
  src/components/Modals/SkipModal.tsx
  src/components/Modals/VoteModal.tsx
  src/components/Modals/index.tsx
Labels: feature

#73 #70 [Feat] 안내문 및 가이드 모달 사진 추가
  public/steps/stepguide1-1.png
  public/steps/stepguide6-1.png
  public/steps/stepguide7-1.png
  src/components/Canvas/TemplateComponent.tsx
  src/components/CanvasLayer/Note.tsx
  src/components/GuideCarousel.tsx
  src/components/Modals/SkipModal.tsx
  src/components/ProcessContent/GuideTextBox.tsx
  src/lib/guideImages.ts
  src/lib/templates.ts
  src/lib/types.ts
Labels: feature

#72 [#71] Feat: 유저메뉴바, 로그아웃 기능 및 UI 구현
  liveblocks.config.ts
  public/default-avatar.png
  public/edit.svg
  public/logout.svg
  public/settings.svg
  src/app/api/liveblocks-auth/route.ts
  src/components/Layout/LeftNav/index.tsx
  src/components/UserInfoSettingBar.tsx
  src/hooks/useLogout.ts
  src/hooks/useToggle.ts
  src/lib/types.ts
Labels: jjunohj, feature, publish

#74 [#40] Feat: 상단바 로그인 정보 적용, Link 버튼 추가, Share 버튼 프로젝트 진입시 생성 등
  src/app/board/layout.tsx
  src/components/Layout/TopNavBar.tsx
Labels: jjunohj, feature

#77 [#76] Feat: 2단계 템플릿 구현 및 storage활용 공유 인풋 폼 완성
  src/components/Canvas/TemplateComponent.tsx
  src/components/ProcessContent/GuideTextBox.tsx
  src/components/ProcessContent/InputFormBox.tsx
  src/components/ProcessContent/NoteBox.tsx
  src/lib/templates.ts
  src/lib/types.ts
Labels: feature

#78 [#75] 프로젝트 생성 폼 로직 및 UI 구현
  liveblocks.config.ts
  package-lock.json
  package.json
  public/x-mark.svg
  src/app/(user)/dashboard/page.tsx
  src/app/api/revalidate/route.ts
  src/app/board/[boardId]/page.tsx
  src/components/Canvas/index.tsx
  src/components/CreateProjectButton.tsx
  src/components/ImageInputBox.tsx
  src/components/Layout/ProcessNav/index.tsx
  src/components/Modals/CompleteModal.tsx
  src/components/Modals/CreateProjectModal.tsx
  src/components/Modals/GuideModal.tsx
  src/components/Modals/SkipModal.tsx
  src/components/Modals/VoteModal.tsx
  src/components/Modals/index.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectCards.tsx
  src/components/Room.tsx
  src/hooks/useGetAuthToken.ts
  src/lib/data.ts
  src/lib/static-data.ts
  src/store/useModalStore.ts
Labels: jjunohj, feature, fix, publish, refactor

#80 [#79] Feat: 프로젝트 삭제 로직, 프로젝트 상세 컴포넌트 UI 구현 | 모달 오류 수정
  public/share.svg
  public/trash.svg
  src/app/board/[boardId]/page.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectDetailBox.tsx
  src/components/Room.tsx
  src/lib/data.ts
  tailwind.config.ts
Labels: jjunohj, feature, fix, publish

#86 [#84] Style: 스타일 관련 수정 (타이머 UI, 툴바 내 스티커 컴포넌트 크기, 컨텐츠 높이)
  public/pause.svg
  public/play.svg
  public/reset.svg
  src/app/(user)/layout.tsx
  src/app/board/layout.tsx
  src/components/CanvasToolBar/StickerButton.tsx
  src/components/Layout/CollabToolAside/Timer.tsx
  src/components/Layout/CollabToolAside/index.tsx
  src/lib/data.ts
  src/lib/utils.ts
  src/utils/formatTimer.ts
Labels: jjunohj, publish, refactor

#82 [#62] Feat: template step3
  liveblocks.config.ts
  src/components/Canvas/TemplateComponent.tsx
  src/components/Canvas/index.tsx
  src/components/Modals/VoteModal.tsx
  src/components/ProcessContent/ThirdStepProb.tsx
  src/components/Room.tsx
  src/lib/templates.ts
  src/lib/types.ts
Labels: feature

#83 [#81] Feat: reactflow 캔버스 내 적용
  liveblocks.config.ts
  package-lock.json
  package.json
  src/app/board/[boardId]/page.tsx
  src/app/layout.tsx
  src/components/Canvas/index.tsx
  src/components/Room.tsx
  src/lib/edges.ts
  src/lib/nodes.ts
Labels: jjunohj, feature

#88 [#87] Feat: 보더 색상 선택 후 드래그 앤 드롭으로 노드 추가 로직 구현
  src/components/Canvas/index.tsx
  src/components/FlowCanvas/DnDFlow/ColorSelector.tsx
  src/components/FlowCanvas/DnDFlow/Sidebar.tsx
  src/components/FlowCanvas/DnDFlow/index.tsx
Labels: jjunohj, feature

#92 [#90] Feat: 페르소나 템플릿 생성, 입력, liveStore 저장
  public/plus-mark.svg
  src/components/Canvas/TemplateComponent.tsx
  src/components/CanvasLayer/Note.tsx
  src/components/ProcessContent/PersonaBox.tsx
  src/components/ProcessContent/ThirdStepProb.tsx
  src/lib/templates.ts
  src/lib/types.ts
Labels: feature

#97 [#91] Feat: Stakeholder 노드 색상 선택, 드래그 앤 드랍 추가, 실시간 라벨 수정 로직 및 UI 구현
  src/components/Canvas/index.tsx
  src/components/FlowCanvas/DnDFlow/FloatingEdge.tsx
  src/components/FlowCanvas/DnDFlow/NodeCreator.tsx
  src/components/FlowCanvas/DnDFlow/StakeholderConnectionLine.tsx
  src/components/FlowCanvas/DnDFlow/StakeholderNode.tsx
  src/components/FlowCanvas/DnDFlow/index.tsx
  src/components/FlowCanvas/DnDFlow/style.css
  src/lib/flow-utils.ts
Labels: jjunohj, feature, publish

#95 [#94] Fix: 프로젝트 생성 시 form-data 형태로 전송 데이터 변경
  src/components/Modals/CreateProjectModal.tsx
Labels: fix

#96 [#93] Feat: Sync 버튼 세부 로직 구현 (인원 확인, 모달 강제 오픈, 스토리지 업데이트, 진행도 체크)
  liveblocks.config.ts
  package-lock.json
  package.json
  public/completed.svg
  src/components/Canvas/index.tsx
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/Common/EventListener.tsx
  src/components/Common/Progress.tsx
  src/components/Layout/CollabToolAside/ProgressBar.tsx
  src/components/Layout/CollabToolAside/Timer.tsx
  src/components/Layout/CollabToolAside/index.tsx
  src/components/Layout/ProcessNav/index.tsx
  src/components/Modals/SyncModal.tsx
  src/components/Modals/index.tsx
  src/components/Room.tsx
  src/hooks/useDeleteLayers.ts
  src/hooks/useDeleteLayersBackspace.ts
Labels: feature

#100 [#99] Feat: 수정가능한 라벨 추가한 커스텀 엣지 구현
  src/components/FlowCanvas/DnDFlow/EdgeLabel.tsx
  src/components/FlowCanvas/DnDFlow/FloatingArrowLabelEdge.tsx
  src/components/FlowCanvas/DnDFlow/StakeholderConnectionLine.tsx
  src/components/FlowCanvas/DnDFlow/StakeholderNode.tsx
  src/components/FlowCanvas/DnDFlow/index.tsx
  src/lib/flow-utils.ts
  src/lib/static-data.ts
Labels: jjunohj, feature, publish

#101 [#98] Feat: Epic Template -> Epic Layer로 변경
  public/PlusMark.tsx
  public/Xmark.tsx
  public/plus-mark.svg
  public/plus.svg
  src/components/Canvas/LayerComponent.tsx
  src/components/Canvas/SelectionBox.tsx
  src/components/Canvas/SelectionTools.tsx
  src/components/CanvasLayer/Epic.tsx
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/CreateProjectButton.tsx
  src/components/Modals/index.tsx
  src/components/ProcessContent/PersonaBox.tsx
  src/components/ProcessContent/ThirdStepProb.tsx
  src/lib/types.ts
  src/utils/processSync.ts
  tailwind.config.ts
Labels: feature, publish

#105 [#103] Feat: 5단계 - WHAT 전체 로직 및 UI 구현
  src/components/Canvas/index.tsx
  src/components/FlowCanvas/DnDFlow/Sidebar.tsx
  src/components/FlowCanvas/DnDFlow/index.tsx
  src/components/ReactFlowCanvas/AnnotationNode.tsx
  src/components/ReactFlowCanvas/ColorSelector.tsx
  src/components/ReactFlowCanvas/EdgeLabel.tsx
  src/components/ReactFlowCanvas/FloatingArrowLabelEdge.tsx
  src/components/ReactFlowCanvas/FloatingEdge.tsx
  src/components/ReactFlowCanvas/InputForWhat.tsx
  src/components/ReactFlowCanvas/MiddleNode.tsx
  src/components/ReactFlowCanvas/NodeCreator.tsx
  src/components/ReactFlowCanvas/StakeholderConnectionLine.tsx
  src/components/ReactFlowCanvas/StakeholderNode.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/components/ReactFlowCanvas/style.css
  src/components/Room.tsx
  src/lib/nodes.ts
Labels: jjunohj, feature, publish

#108 [#107] Feat: WHY, HOW 단계 템플릿 구현
  src/components/ReactFlowCanvas/InputForWhat.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/nodes.ts
Labels: jjunohj, feature, publish

#114 [#113] Fix: SendBird 기능 정상화, 커서 위치 조정, 콘솔 내 svg layout 경고문 이슈 해결
  src/app/board/layout.tsx
  src/components/Layout/CollabToolAside/GroupCall/GroupCallButton.tsx
  src/components/Layout/CollabToolAside/GroupCall/LiveCallUser.tsx
  src/components/Layout/CollabToolAside/MusicPlayer/index.tsx
  src/components/Layout/TopNavBar.tsx
  src/lib/utils.ts
Labels: bug, jjunohj, fix

#112 [#109] Feat: 메뉴트리 템플릿 로직 및 UI 구현
  src/components/ReactFlowCanvas/Node/AnnotationNode.tsx
  src/components/ReactFlowCanvas/Node/ContentNode.tsx
  src/components/ReactFlowCanvas/Node/MiddleNode.tsx
  src/components/ReactFlowCanvas/Node/PageNode.tsx
  src/components/ReactFlowCanvas/Node/StakeholderNode.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/nodes.ts
Labels: jjunohj, feature, publish

#125 [#124] Fix: 대시보드 새로고침 개선
  src/components/Modals/CreateProjectModal.tsx
  src/components/ProjectDetailBox.tsx
Labels: bug, fix, refactor

#126 [#123] Style: 전체적인 템플릿 스타일 보완
  src/components/Canvas/index.tsx
  src/components/ProcessContent/InputFormBox.tsx
  src/components/ProcessContent/NoteBox.tsx
  src/components/ReactFlowCanvas/Node/AnnotationNode.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/lib/nodes.ts
  src/lib/static-data.ts
  src/lib/templates.ts
Labels: jjunohj, publish

#129 [#127] Style: 전체 모달 리퍼블리싱, 투표 닫기 버튼 공통화
  package-lock.json
  package.json
  public/lotties/check.json
  public/lotties/writing.json
  src/app/globals.css
  src/components/Modals/CompleteModal.tsx
  src/components/Modals/ProcessingScenarioModal.tsx
  src/components/Modals/SyncModal.tsx
  src/components/Modals/VoteModal.tsx
  src/components/Modals/index.tsx
  src/lib/templates.ts
Labels: jjunohj, feature, publish

#135 [133] Refactor: 사용성 개선, 프로세스 버튼 로직 수정, 12단계 완료시 모달 추가
  liveblocks.config.ts
  src/components/Canvas/TemplateComponent.tsx
  src/components/CanvasToolBar/SkipButton.tsx
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/CanvasToolBar/VoteButton.tsx
  src/components/Common/EventListener.tsx
  src/components/Layout/TopNavBar.tsx
  src/components/Modals/CompleteModal.tsx
  src/components/Modals/VoteCompleteModal.tsx
  src/components/Modals/VoteEndModal.tsx
  src/components/Modals/VoteModal.tsx
  src/components/Modals/index.tsx
  src/components/ProcessContent/VoteBox.tsx
Labels: feature, fix, refactor

#137 [#136] Feat: 기획 완료 모달 구현, 가이드 모달 리퍼블리시
  public/lotties/clap.json
  public/lotties/confetti.json
  src/components/Canvas/index.tsx
  src/components/CanvasToolBar/SyncButton.tsx
  src/components/Modals/CompleteModal.tsx
  src/components/Modals/GuideModal.tsx
  src/components/Modals/index.tsx
  src/components/ReactFlowCanvas/Node/AnnotationNode.tsx
  src/components/ReactFlowCanvas/Node/AreaNode.tsx
Labels: jjunohj, feature, publish

#139 [#138] Fix: 커서 끝 색깔 다른 이슈 수정
  src/components/Canvas/Cursor.tsx
Labels: jjunohj, fix, publish

#141 docs: 리드미 추가
  README.md
Labels: jjunohj

#145 [Feat] 144: GoogleAnalytics, Clarity 도입 Script 컴포넌트
  src/app/layout.tsx
  src/metrics/GoogleAnalytics.tsx
  src/metrics/MicrosoftClarity.tsx
  src/metrics/index.tsx
Labels: feature
