Repository i-Dear/sync-d-frontend, pull requests merged in 2024-04, with the labels that each got.

#12 [#11] Feat: 목로그인 구현 (목업 유저데이터 DB, 목업 로그인 API, Login 페이지, Dashboard 페이지)
  db.json
  liveblocks.config.ts
  package-lock.json
  package.json
  src/app/api/mock-auth/route.ts
  src/app/dashboard/[userId]/page.tsx
  src/app/login/page.tsx
  src/components/Room.tsx
  src/hooks/useAuth.tsx
  src/hooks/useUserInfoStore.tsx
Labels: jjunohj, feature

#19 [#18] Feat: Text 컴포넌트 틀 구현, 툴바 아이콘에 컴포넌트 부착
  src/components/Canvas.tsx
  src/components/LayerComponent.tsx
  src/components/Note.tsx
  src/components/Text.tsx
  src/components/ToolsBar/index.tsx
  src/lib/types.ts
Labels: jjunohj, feature, fix

#22 [#21] Feat: 우측 상단 LiveAvatars, 각 단계별 ProcessAvatars 구현
  liveblocks.config.ts
  next.config.mjs
  package-lock.json
  package.json
  src/components/Avatar.tsx
  src/components/Canvas.tsx
  src/components/LiveAvatars.tsx
  src/components/ProcessAvatars.tsx
  src/components/ProcessSideNav.tsx
  src/components/Room.tsx
  tailwind.config.ts
Labels: jjunohj, feature

#29 [#24] Feat: 공용 타이머 컴포넌트 구현
  .prettierrc
  liveblocks.config.ts
  package-lock.json
  package.json
  src/components/ProcessSideNav.tsx
  src/components/Room.tsx
  src/components/Timer.tsx
  src/utils/formatTimer.ts
Labels: feature

#30 [#28] Feat: 스티커 컴포넌트 구현
  next.config.mjs
  src/components/Canvas.tsx
  src/components/IconButton.tsx
  src/components/LayerComponent.tsx
  src/components/SelectionTools.tsx
  src/components/Sticker.tsx
  src/components/StickerPicker.tsx
  src/components/Timer.tsx
  src/components/ToolsBar/StickerButton.tsx
  src/components/ToolsBar/index.tsx
  src/lib/sticker.json
  src/lib/types.ts
  src/store/useStickerSrcStore.ts
Labels: feature

#27 [#26] Feat: 프로젝트 내 음성통화 컴포넌트 구현
  db.json
  liveblocks.config.ts
  package-lock.json
  package.json
  public/mute-off.svg
  src/app/dashboard/[userId]/page.tsx
  src/app/login/page.tsx
  src/components/Canvas.tsx
  src/components/GroupCall/GroupCallButton.tsx
  src/components/GroupCall/LiveCallUser.tsx
  src/components/GroupCall/LiveCallUsers.tsx
  src/components/GroupCall/index.tsx
  src/components/MusicPlayer.tsx
  src/components/Room.tsx
  src/hooks/useSendBirdCall.tsx
  src/hooks/useUserInfoStore.tsx
  src/lib/types.ts
  src/lib/utils.ts
Labels: jjunohj, feature, fix

#34 [#33] Feat: 프로젝트 내 음성통화 로직 구현 및 UI 퍼블리싱
  src/app/globals.css
  src/components/Canvas.tsx
  src/components/GroupCall/GroupCallButton.tsx
  src/components/GroupCall/LiveCallUser.tsx
  src/components/GroupCall/LiveCallUsers.tsx
  src/components/GroupCall/index.tsx
  src/components/RightSideToolsBar.tsx
  tailwind.config.ts
Labels: jjunohj, feature

#39 [#35] Feat: 프로젝트 내 MusicPlayer UI 구현
  public/mute-off.svg
  public/mute.svg
  src/components/Canvas.tsx
  src/components/GroupCall/index.tsx
  src/components/LiveAvatars.tsx
  src/components/MusicPlayer.tsx
  src/components/RightSideToolsBar.tsx
  src/components/WaveForm.tsx
  tailwind.config.ts
Labels: jjunohj, feature, publish
